-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: AdventureWorksDB, v50 by priyank.singh@sqldbm.com *


CREATE FILE FORMAT fileFormat_431
 TYPE = JSON;

-- ************************************** EDW.DimOrganization
CREATE TABLE EDW.DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentOrganizationKey number(38,0),
 PercentageOfOwnership varchar(16),
 OrganizationName      varchar(50),
 CurrencyKey           number(38,0),
 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';

-- ************************************** EDW.DimGeography
CREATE TABLE EDW.DimGeography
(
 GeographyKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 City                     varchar(30),
 StateProvinceCode        varchar(3),
 StateProvinceName        varchar(50),
 CountryRegionCode        varchar(3),
 EnglishCountryRegionName varchar(50),
 SpanishCountryRegionName varchar(50),
 FrenchCountryRegionName  varchar(50),
 PostalCode               varchar(15),
 SalesTerritoryKey        number(38,0),
 IpAddressLocator         varchar(15),
 CONSTRAINT PK_DimGeography PRIMARY KEY ( GeographyKey )
);

-- ************************************** EDW.DimEmployee
CREATE TABLE EDW.DimEmployee
(
 EmployeeKey                          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentEmployeeKey                    number(38,0),
 EmployeeNationalIDAlternateKey       varchar(15),
 ParentEmployeeNationalIDAlternateKey varchar(15),
 SalesTerritoryKey                    number(38,0),
 FirstName                            varchar(50) NOT NULL,
 LastName                             varchar(50) NOT NULL,
 MiddleName                           varchar(50),
 NameStyle                            number(38,0) NOT NULL,
 Title                                varchar(50),
 HireDate                             date,
 BirthDate                            date,
 LoginID                              varchar(256),
 EmailAddress                         varchar(50),
 Phone                                varchar(25),
 MaritalStatus                        varchar(1),
 EmergencyContactName                 varchar(50),
 EmergencyContactPhone                varchar(25),
 SalariedFlag                         number(38,0),
 Gender                               varchar(1),
 PayFrequency                         number(38,0),
 BaseRate                             number(38,0),
 VacationHours                        number(38,0),
 SickLeaveHours                       number(38,0),
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL,
 DepartmentName                       varchar(50),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(50),
 CONSTRAINT PK_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_403 FOREIGN KEY ( ParentEmployeeKey ) REFERENCES EDW.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.DimSalesTerritory ( SalesTerritoryKey )
)
COMMENT = 'This table holds all Employee Information';

-- ************************************** EDW.SampleView
CREATE VIEW EDW.SampleView

  Comment = 'This is SampleView Comment'

AS
(
    -- Please type View Definition here
    SELECT 
           FinanceKey, 
           OrganizationKey,  
           AccountKey, 
           ScenarioKey
    FROM 
        EDW.FactFinance ff
         
);

