-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: AdventureWorksDB, v50 by priyank.singh@sqldbm.com *


CREATE FILE FORMAT fileFormat_431
 TYPE = JSON;

-- ************************************** EDW.DimProductCategory
CREATE TABLE EDW.DimProductCategory
(
 ProductCategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductCategoryAlternateKey number(38,0),
 EnglishProductCategoryName  varchar(50) NOT NULL,
 SpanishProductCategoryName  varchar(50) NOT NULL,
 FrenchProductCategoryName   varchar(50) NOT NULL,
 CONSTRAINT PK_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);

-- ************************************** EDW.DimProductSubcategory
CREATE TABLE EDW.DimProductSubcategory
(
 ProductSubcategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductSubcategoryAlternateKey number(38,0),
 EnglishProductSubcategoryName  varchar(50) NOT NULL,
 SpanishProductSubcategoryName  varchar(50) NOT NULL,
 FrenchProductSubcategoryName   varchar(50) NOT NULL,
 ProductCategoryKey             number(38,0),
 CONSTRAINT PK_DimProductSubcategory PRIMARY KEY ( ProductSubcategoryKey ),
 CONSTRAINT FK_DimProductSubcategory_409 FOREIGN KEY ( ProductCategoryKey ) REFERENCES EDW.DimProductCategory ( ProductCategoryKey )
);

-- ************************************** EDW.DimProduct
CREATE TABLE EDW.DimProduct
(
 ProductKey            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductAlternateKey   varchar(25),
 ProductSubcategoryKey number(38,0),
 WeightUnitMeasureCode varchar(3),
 SizeUnitMeasureCode   varchar(3),
 EnglishProductName    varchar(50) NOT NULL,
 SpanishProductName    varchar(50),
 FrenchProductName     varchar(50),
 StandardCost          number(38,0),
 FinishedGoodsFlag     number(38,0) NOT NULL,
 Color                 varchar(15) NOT NULL,
 SafetyStockLevel      number(38,0),
 ReorderPoint          number(38,0),
 ListPrice             number(38,0),
 Size                  varchar(50),
 SizeRange             varchar(50),
 Weight                float,
 DaysToManufacture     number(38,0),
 ProductLine           varchar(2),
 DealerPrice           number(38,0),
 Class                 varchar(2),
 Style                 varchar(2),
 ModelName             varchar(50),
 EnglishDescription    varchar(400),
 FrenchDescription     varchar(400),
 ChineseDescription    varchar(400),
 ArabicDescription     varchar(400),
 HebrewDescription     varchar(400),
 ThaiDescription       varchar(400),
 GermanDescription     varchar(400),
 JapaneseDescription   varchar(400),
 TurkishDescription    varchar(400),
 Status                varchar(7),
 CONSTRAINT PK_DimProduct PRIMARY KEY ( ProductKey ),
 CONSTRAINT FK_DimProduct_407 FOREIGN KEY ( ProductSubcategoryKey ) REFERENCES EDW.DimProductSubcategory ( ProductSubcategoryKey )
);

-- ************************************** EDW.SampleView
CREATE VIEW EDW.SampleView

  Comment = 'This is SampleView Comment'

AS
(
    -- Please type View Definition here
    SELECT 
           FinanceKey, 
           OrganizationKey,  
           AccountKey, 
           ScenarioKey
    FROM 
        EDW.FactFinance ff
         
);

