-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: AdventureWorksDB, v54 by priyank.singh@sqldbm.com *


-- ************************************** EDW.DimAccount
CREATE TABLE EDW.DimAccount
(
 AccountKey                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 ParentAccountKey              number(38,0) COMMENT 'Identifier of parent Account',
 AccountCodeAlternateKey       number(38,0),
 ParentAccountCodeAlternateKey number(38,0) COMMENT 'Desc',
 AccountDescription            varchar(50) COMMENT 'Desc',
 AccountType                   varchar(50) COMMENT 'Desc',
 Operator                      varchar(50) COMMENT 'Desc',
 CustomMembers                 varchar(300),
 ValueType                     varchar(50),
 CustomMemberOptions           varchar(200),
 CONSTRAINT PK_DimAccount PRIMARY KEY ( AccountKey )
)
COMMENT = 'Holds all Account information';

-- ************************************** EDW.Country
CREATE TABLE EDW.Country
(
 countryId numeric NOT NULL,
 cityId    numeric NOT NULL,
 city      varchar(50) NOT NULL,
 CONSTRAINT PK_country PRIMARY KEY ( countryId )
);

-- ************************************** EDW.City
CREATE TABLE EDW.City
(
 cityId    numeric NOT NULL COMMENT 'Unique identification',
 city      varchar NOT NULL COMMENT 'Name of the city',
 countryId numeric NOT NULL COMMENT 'id of the country where city belongs to',
 CONSTRAINT PK_city PRIMARY KEY ( cityId ),
 CONSTRAINT FK_452 FOREIGN KEY ( countryId ) REFERENCES EDW.Country ( countryId )
)
COMMENT = 'Capturing city information all over world';

-- ************************************** EDW.Address
CREATE TABLE EDW.Address
(
 AddressID    numeric NOT NULL,
 AddressLine1 varchar NOT NULL,
 AddressLine2 varchar NOT NULL,
 state        varchar(50) NOT NULL,
 postalcode   numeric NOT NULL,
 cityId       numeric NOT NULL,
 CONSTRAINT PK_address PRIMARY KEY ( AddressID ),
 CONSTRAINT FK_457 FOREIGN KEY ( cityId ) REFERENCES EDW.City ( cityId )
);

-- ************************************** EDW.SampleView
CREATE VIEW EDW.SampleView

  Comment = 'This is SampleView Comment'

AS
(
    -- Please type View Definition here
    SELECT 
           FinanceKey, 
           OrganizationKey,  
           AccountKey, 
           ScenarioKey
    FROM 
        EDW.FactFinance ff
         
);

